name: GitHub Actions CI/CD
run-name: Linter C++ code
on: 
  push:
    branches:
      - main
jobs:
  linter:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - name: Server and repository information
        run: |
          echo "The job was automatically triggered by a ${{ github.event_name }} event.";
          echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!";
          echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}.";
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Repository cloned successfully
        run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: Ready to run commands
        run: echo "Ready to run commands"
      - name: Super-linter
        uses: super-linter/super-linter@v6.3.0  # x-release-please-version
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
